[shell_environment_policy]
inherit = "core"

[shell_environment_policy.set]
FXBOT_DOCS_SYNC_CHECKS = "on"
FXBOT_PRESTOP_CHECKS = "on"
INTEGRATION_TEST_DB_URL = "postgres://fxbot:fxbot@localhost:5432/fxbot_test?sslmode=disable"
