// cmd/spread-calibrate は market_summaries の live スプレッド観測値から
// backtest 用の時間帯別スプレッド較正ファイル (YAML) を生成する read-only ツール
// (中央値 0.5pip + 東京オープン spike ~10pips の混合モデルの較正側)。
//
// ⚠️ 較正データの週末汚染: market_summaries には
// 閉場 (週末) snapshot に spread 10-11pips が混入していた実例があるため、
// IsFXMarketClosedJST で閉場サンプルを必ず除外する。
//
// 使い方:
//
//	go run ./cmd/spread-calibrate \
//	    -since 2026-01-01T00:00:00Z -symbols USD_JPY,EUR_JPY -min-count 5 \
//	    -out runtime/spread_calibration.yaml
//
// DB は SELECT のみ (DATABASE_URL_RO があればそちらを優先)。書き戻しはしない。
package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"

	"fx-bot/backend/internal/config"
	"fx-bot/backend/internal/domain/market"
)

// jstZone は JST 固定ゾーン (+09:00)。DB の created_at は UTC 保存なので
// 時間帯バケツ分けの前に必ずこのゾーンへ変換する。
var jstZone = time.FixedZone("JST", 9*60*60)

// Sample は market_summaries 1 行ぶんのスプレッド観測値。
type Sample struct {
	At         time.Time // created_at (UTC 保存 → 判定時に JST 変換)
	SpreadPips float64   // raw_json の current_rate.spread_pips
}

// IsFXMarketClosedJST は FX 閉場ウィンドウ (≈ 土曜 06:00 JST 〜 月曜 05:00 JST) か
// を返す。境界の定義は domain/market.IsForexOpen (リポジトリ唯一の真実) に委譲し、
// 二つの市場ウィンドウ定義が drift しないようにする。
//   - 土曜側 06:00 JST: NY クローズは夏時間で土曜 06:00 JST / 冬時間で 07:00 JST。
//     06:00 を境界にすると冬の 06:00-07:00 (まだ開場) も閉場扱いで捨てるが、
//     較正用途では疑わしいサンプルを捨てる方向 (保守的) に倒すのが正しい。
//   - 月曜側 05:00 JST: ウェリントン/GMO の週明けクォート再開はおおむね月曜早朝。
//     東京オープン帯 (05-08 JST) の実スプレッド spike を較正対象に残す。
func IsFXMarketClosedJST(t time.Time) bool {
	return !market.IsForexOpen(t)
}

// MedianByHourJST は JST の時間帯 (0-23) ごとのスプレッド中央値とサンプル数を返す。
// 閉場サンプル (週末汚染) と非正値 (spread <= 0) はカウントせず除外する。
// サンプルが無い hour は byHour 0 / counts 0 のまま。
func MedianByHourJST(samples []Sample) (byHour [24]float64, counts [24]int) {
	var buckets [24][]float64
	for _, s := range samples {
		if s.SpreadPips <= 0 || IsFXMarketClosedJST(s.At) {
			continue
		}
		h := s.At.In(jstZone).Hour()
		buckets[h] = append(buckets[h], s.SpreadPips)
	}
	for h, vals := range buckets {
		counts[h] = len(vals)
		if len(vals) > 0 {
			byHour[h] = medianOf(vals)
		}
	}
	return byHour, counts
}

// OverallMedian は (開場かつ正値の) 全サンプルの中央値と件数を返す。
// fallback_pips (= by_hour_jst に無い hour のフォールバック値) の算出に使う。
func OverallMedian(samples []Sample) (float64, int) {
	vals := make([]float64, 0, len(samples))
	for _, s := range samples {
		if s.SpreadPips <= 0 || IsFXMarketClosedJST(s.At) {
			continue
		}
		vals = append(vals, s.SpreadPips)
	}
	if len(vals) == 0 {
		return 0, 0
	}
	return medianOf(vals), len(vals)
}

// medianOf は中央値 (偶数個なら中央 2 値の平均)。入力は破壊しない。
func medianOf(vals []float64) float64 {
	sorted := make([]float64, len(vals))
	copy(sorted, vals)
	sort.Float64s(sorted)
	n := len(sorted)
	if n%2 == 1 {
		return sorted[n/2]
	}
	return (sorted[n/2-1] + sorted[n/2]) / 2.0
}

// yamlHeader は出力 YAML の先頭コメント。較正の出自と週末除外を明記する
// (YAML コメントなので sibling の backtest loader のパースには影響しない)。
const yamlHeader = "# generated by spread-calibrate; weekend/closed-market samples excluded\n"

// RenderSpreadYAML は較正結果を backtest loader が読む固定フォーマットで出力する。
// フォーマット契約 (sibling の internal/backtest loader と共有 — 変更禁止):
//
//	spreads:
//	  USD_JPY:
//	    fallback_pips: 0.5
//	    by_hour_jst:
//	      0: 0.6
//	      5: 9.8
//
// counts[symbol][hour] < minCount の hour は by_hour_jst から省略する
// (loader 側は fallback_pips に落ちる)。全 hour が minCount 未満なら
// by_hour_jst キーごと省略。symbol はアルファベット順で安定出力。
func RenderSpreadYAML(perSymbol map[string][24]float64, fallback map[string]float64, minCount int, counts map[string][24]int) string {
	symbols := make([]string, 0, len(perSymbol))
	for sym := range perSymbol {
		symbols = append(symbols, sym)
	}
	sort.Strings(symbols)

	var b strings.Builder
	b.WriteString(yamlHeader)
	b.WriteString("spreads:\n")
	for _, sym := range symbols {
		byHour := perSymbol[sym]
		cnt := counts[sym]
		fmt.Fprintf(&b, "  %s:\n", sym)
		fmt.Fprintf(&b, "    fallback_pips: %s\n", formatPips(fallback[sym]))

		hasQualified := false
		for h := 0; h < 24; h++ {
			if cnt[h] >= minCount {
				hasQualified = true
				break
			}
		}
		if !hasQualified {
			continue
		}
		b.WriteString("    by_hour_jst:\n")
		for h := 0; h < 24; h++ {
			if cnt[h] < minCount {
				continue
			}
			fmt.Fprintf(&b, "      %d: %s\n", h, formatPips(byHour[h]))
		}
	}
	return b.String()
}

// formatPips は 0.001 pips に丸めて余計な浮動小数点桁を出さない
// (中央値の平均で 0.6000000000000001 のような誤差桁が出るのを防ぐ)。
func formatPips(v float64) string {
	rounded := float64(int64(v*1000+0.5)) / 1000 // v >= 0 前提 (spread は正値のみ)
	return strconv.FormatFloat(rounded, 'f', -1, 64)
}

// extractSpreadPips は market_summaries.raw_json (= market.MarketSummary の
// serialize 結果) から current_rate.spread_pips だけを最小 struct で取り出す。
// JSON タグは internal/domain/market/summary.go の定義に一致させる。
func extractSpreadPips(raw []byte) (float64, error) {
	var s struct {
		CurrentRate struct {
			SpreadPips float64 `json:"spread_pips"`
		} `json:"current_rate"`
	}
	if err := json.Unmarshal(raw, &s); err != nil {
		return 0, fmt.Errorf("parse raw_json: %w", err)
	}
	return s.CurrentRate.SpreadPips, nil
}

// splitSymbolsCSV は -symbols の CSV を trim して空要素を捨てる。全部空なら nil。
func splitSymbolsCSV(csv string) []string {
	var out []string
	for _, s := range strings.Split(csv, ",") {
		s = strings.TrimSpace(s)
		if s != "" {
			out = append(out, s)
		}
	}
	return out
}

// cliFlags はテスト可能にした CLI 入力 (cmd/backtest の cliFlags 流儀に合わせる)。
type cliFlags struct {
	since    string // RFC3339。空なら now-30d
	symbols  string // CSV
	minCount int
	out      string // 空なら stdout
	envPath  string
}

func main() {
	f := cliFlags{}
	flag.StringVar(&f.since, "since", "", "observations since (RFC3339, default: 30 days ago)")
	flag.StringVar(&f.symbols, "symbols", "USD_JPY,EUR_JPY,GBP_JPY,EUR_USD,GBP_USD", "comma-separated symbols")
	flag.IntVar(&f.minCount, "min-count", 5, "min samples per hour to include in by_hour_jst")
	flag.StringVar(&f.out, "out", "", "output file path (default: stdout)")
	flag.StringVar(&f.envPath, "env", ".env", "path to .env")
	flag.Parse()

	if err := run(f); err != nil {
		fmt.Fprintln(os.Stderr, "spread-calibrate:", err)
		os.Exit(1)
	}
}

func run(f cliFlags) error {
	// --- バリデーション (DB に触る前に落とす) ---
	since := time.Now().UTC().AddDate(0, 0, -30)
	if f.since != "" {
		t, err := time.Parse(time.RFC3339, f.since)
		if err != nil {
			return fmt.Errorf("-since: %w", err)
		}
		since = t
	}
	symbols := splitSymbolsCSV(f.symbols)
	if len(symbols) == 0 {
		return fmt.Errorf("-symbols must list at least one symbol")
	}
	if f.minCount < 1 {
		return fmt.Errorf("-min-count must be >= 1")
	}

	// --- read-only DB 接続 (DATABASE_URL_RO 優先 = SELECT-only ロール fxbot_ro) ---
	if err := config.LoadDotEnv(f.envPath); err != nil {
		fmt.Fprintf(os.Stderr, "warn: load %s: %v (continuing with env)\n", f.envPath, err)
	}
	dsn := os.Getenv("DATABASE_URL_RO")
	if dsn == "" {
		dsn = os.Getenv("DATABASE_URL")
	}
	if dsn == "" {
		return fmt.Errorf("DATABASE_URL_RO or DATABASE_URL env var is required")
	}

	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()
	pool, err := pgxpool.New(ctx, dsn)
	if err != nil {
		return fmt.Errorf("connect db: %w", err)
	}
	defer pool.Close()

	// SELECT のみ (CLAUDE.md: live DB は read-only)。
	rows, err := pool.Query(ctx,
		`SELECT symbol, raw_json, created_at
		   FROM market_summaries
		  WHERE created_at >= $1 AND symbol = ANY($2)`,
		since, symbols)
	if err != nil {
		return fmt.Errorf("query market_summaries: %w", err)
	}
	defer rows.Close()

	samplesBySymbol := make(map[string][]Sample, len(symbols))
	parseFails := 0
	total := 0
	for rows.Next() {
		var (
			symbol    string
			rawJSON   []byte
			createdAt time.Time
		)
		if err := rows.Scan(&symbol, &rawJSON, &createdAt); err != nil {
			return fmt.Errorf("scan: %w", err)
		}
		total++
		spread, err := extractSpreadPips(rawJSON)
		if err != nil {
			parseFails++
			continue
		}
		samplesBySymbol[symbol] = append(samplesBySymbol[symbol], Sample{At: createdAt, SpreadPips: spread})
	}
	if err := rows.Err(); err != nil {
		return fmt.Errorf("rows: %w", err)
	}

	// --- 集計 ---
	perSymbol := make(map[string][24]float64)
	fallback := make(map[string]float64)
	counts := make(map[string][24]int)
	for _, sym := range symbols {
		samples := samplesBySymbol[sym]
		med, n := OverallMedian(samples)
		if n == 0 {
			fmt.Fprintf(os.Stderr, "warn: %s: no market-open samples since %s — skipped\n",
				sym, since.Format(time.RFC3339))
			continue
		}
		byHour, cnt := MedianByHourJST(samples)
		perSymbol[sym] = byHour
		fallback[sym] = med
		counts[sym] = cnt
	}
	fmt.Fprintf(os.Stderr, "rows=%d parse_fails=%d symbols_with_data=%d since=%s\n",
		total, parseFails, len(perSymbol), since.Format(time.RFC3339))

	// --- 出力 ---
	yaml := RenderSpreadYAML(perSymbol, fallback, f.minCount, counts)
	if f.out == "" {
		fmt.Print(yaml)
		return nil
	}
	if err := os.WriteFile(f.out, []byte(yaml), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", f.out, err)
	}
	fmt.Fprintf(os.Stderr, "wrote %s\n", f.out)
	return nil
}
