// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_advisor_runs.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLastAdvisorDurationMs = `-- name: GetLastAdvisorDurationMs :one
SELECT (EXTRACT(EPOCH FROM (finished_at - started_at)) * 1000)::int8 AS duration_ms
FROM ai_advisor_runs
WHERE status = 'success'
ORDER BY finished_at DESC
LIMIT 1
`

// Dashboard 用: 直近の成功 advisor run の duration_ms。
func (q *Queries) GetLastAdvisorDurationMs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getLastAdvisorDurationMs)
	var duration_ms int64
	err := row.Scan(&duration_ms)
	return duration_ms, err
}

const insertAdvisorRun = `-- name: InsertAdvisorRun :exec
INSERT INTO ai_advisor_runs (
  run_id, provider, mode, prompt_path,
  status, source, started_at, finished_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAdvisorRunParams struct {
	RunID      string
	Provider   string
	Mode       string
	PromptPath string
	Status     string
	Source     string
	StartedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
}

func (q *Queries) InsertAdvisorRun(ctx context.Context, arg InsertAdvisorRunParams) error {
	_, err := q.db.Exec(ctx, insertAdvisorRun,
		arg.RunID,
		arg.Provider,
		arg.Mode,
		arg.PromptPath,
		arg.Status,
		arg.Source,
		arg.StartedAt,
		arg.FinishedAt,
	)
	return err
}

const insertAdvisorRunError = `-- name: InsertAdvisorRunError :exec
INSERT INTO advisor_run_errors (run_id, message)
VALUES ($1, $2)
`

type InsertAdvisorRunErrorParams struct {
	RunID   string
	Message string
}

func (q *Queries) InsertAdvisorRunError(ctx context.Context, arg InsertAdvisorRunErrorParams) error {
	_, err := q.db.Exec(ctx, insertAdvisorRunError, arg.RunID, arg.Message)
	return err
}

const insertAdvisorRunIO = `-- name: InsertAdvisorRunIO :exec
INSERT INTO advisor_run_io (run_id, input_json, output_yaml)
VALUES ($1, $2, $3)
`

type InsertAdvisorRunIOParams struct {
	RunID      string
	InputJson  []byte
	OutputYaml string
}

func (q *Queries) InsertAdvisorRunIO(ctx context.Context, arg InsertAdvisorRunIOParams) error {
	_, err := q.db.Exec(ctx, insertAdvisorRunIO, arg.RunID, arg.InputJson, arg.OutputYaml)
	return err
}
