// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: candles.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listCandlesSince = `-- name: ListCandlesSince :many
SELECT id, symbol, timeframe, opened_at, open, high, low, close, volume, created_at, updated_at
FROM candles
WHERE symbol = $1 AND timeframe = $2 AND opened_at >= $3
ORDER BY opened_at DESC
LIMIT $4
`

type ListCandlesSinceParams struct {
	Symbol    string
	Timeframe string
	OpenedAt  pgtype.Timestamptz
	Limit     int32
}

func (q *Queries) ListCandlesSince(ctx context.Context, arg ListCandlesSinceParams) ([]Candle, error) {
	rows, err := q.db.Query(ctx, listCandlesSince,
		arg.Symbol,
		arg.Timeframe,
		arg.OpenedAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Candle
	for rows.Next() {
		var i Candle
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.Timeframe,
			&i.OpenedAt,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.Volume,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCandle = `-- name: UpsertCandle :exec
INSERT INTO candles (symbol, timeframe, opened_at, open, high, low, close, volume)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (symbol, timeframe, opened_at) DO UPDATE SET
    open       = EXCLUDED.open,
    high       = EXCLUDED.high,
    low        = EXCLUDED.low,
    close      = EXCLUDED.close,
    volume     = EXCLUDED.volume,
    updated_at = now()
`

type UpsertCandleParams struct {
	Symbol    string
	Timeframe string
	OpenedAt  pgtype.Timestamptz
	Open      float64
	High      float64
	Low       float64
	Close     float64
	Volume    float64
}

func (q *Queries) UpsertCandle(ctx context.Context, arg UpsertCandleParams) error {
	_, err := q.db.Exec(ctx, upsertCandle,
		arg.Symbol,
		arg.Timeframe,
		arg.OpenedAt,
		arg.Open,
		arg.High,
		arg.Low,
		arg.Close,
		arg.Volume,
	)
	return err
}
