// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: market_summaries.sql

package dbgen

import (
	"context"
)

const insertMarketSummary = `-- name: InsertMarketSummary :exec
INSERT INTO market_summaries (symbol, summary_window, raw_json)
VALUES ($1, $2, $3)
`

type InsertMarketSummaryParams struct {
	Symbol        string
	SummaryWindow string
	RawJson       []byte
}

func (q *Queries) InsertMarketSummary(ctx context.Context, arg InsertMarketSummaryParams) error {
	_, err := q.db.Exec(ctx, insertMarketSummary, arg.Symbol, arg.SummaryWindow, arg.RawJson)
	return err
}
