// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdvisorRunError struct {
	RunID   string
	Message string
}

type AdvisorRunIo struct {
	RunID      string
	InputJson  []byte
	OutputYaml string
}

type AiAdvisorRun struct {
	ID         int64
	RunID      string
	Provider   string
	Mode       string
	PromptPath string
	Status     string
	Source     string
	StartedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
}

type Candle struct {
	ID        int64
	Symbol    string
	Timeframe string
	OpenedAt  pgtype.Timestamptz
	Open      float64
	High      float64
	Low       float64
	Close     float64
	Volume    float64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ConfigValidationEvent struct {
	ID             int64
	ConfigID       string
	ValidationType string
	Status         string
	Message        *string
	CreatedAt      pgtype.Timestamptz
}

type ManualPosition struct {
	PositionID int64
	CreatedAt  pgtype.Timestamptz
}

type MarketSummary struct {
	ID            int64
	Symbol        string
	SummaryWindow string
	RawJson       []byte
	CreatedAt     pgtype.Timestamptz
}

type Position struct {
	ID                               int64
	Symbol                           string
	Side                             string
	Quantity                         int32
	EntryPrice                       float64
	TakeProfitPips                   float64
	StopLossPips                     float64
	MaxHoldMinutes                   int32
	ExtensionMaxMinutes              int32
	ExtensionUnrealizedPipsThreshold float64
	StrategyConfigID                 string
	Status                           string
	OpenedAt                         pgtype.Timestamptz
	CreatedAt                        pgtype.Timestamptz
	UpdatedAt                        pgtype.Timestamptz
	EarlyExitWindowMinutes           int32
	EarlyExitTargetPips              float64
	RatchetArmPips                   float64
	RatchetGivebackPips              float64
	PeakUnrealizedPips               float64
	RatchetArmed                     bool
	EntryFeeJpy                      *float64
	EntrySpreadPips                  *float64
	EntrySlippagePips                *float64
	TroughUnrealizedPips             float64
	LossRatchetArmed                 bool
}

type PositionStateEvent struct {
	PositionID     int64
	State          string
	TransitionedAt pgtype.Timestamptz
}

type PositionsLive struct {
	PositionID       int64
	BrokerPositionID string
	TpOrderID        string
	SlOrderID        string
}

type RecoveredPosition struct {
	PositionID     int64
	RecoveryReason string
	RecoveredAt    pgtype.Timestamptz
}

type SignalRejection struct {
	ID               int64
	StrategyConfigID string
	Reason           string
	Detail           []byte
	CreatedAt        pgtype.Timestamptz
}

type StrategyConfig struct {
	ID                     int64
	ConfigID               string
	Source                 string
	Mode                   string
	Symbol                 string
	Enabled                bool
	MarketRegimeType       *string
	MarketRegimeConfidence float64
	StrategyName           *string
	ValidFrom              pgtype.Timestamptz
	ValidUntil             pgtype.Timestamptz
	RawYaml                string
	Status                 string
	CreatedAt              pgtype.Timestamptz
}

type StrategyConfigActivation struct {
	ConfigID    string
	ActivatedAt pgtype.Timestamptz
}

type StrategyConfigParseFailure struct {
	ConfigID  string
	RawInput  string
	CreatedAt pgtype.Timestamptz
}

type StrategyConfigRejection struct {
	ConfigID  string
	Reason    string
	CreatedAt pgtype.Timestamptz
}

type Trade struct {
	ID               int64
	PositionID       int64
	StrategyConfigID string
	Symbol           string
	Side             string
	Quantity         int32
	EntryPrice       float64
	ExitPrice        float64
	ProfitLossPips   float64
	ProfitLossJpy    float64
	CloseReason      string
	OpenedAt         pgtype.Timestamptz
	ClosedAt         pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	FeeJpy           float64
	SwapJpy          float64
	FeeEstimated     bool
}

type TradeSignal struct {
	TradeID  int64
	SignalID string
}
