// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: positions.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPositionForClose = `-- name: ClaimPositionForClose :execrows
UPDATE positions
SET status = 'CLOSING', updated_at = now()
WHERE id = $1 AND status = 'OPEN'
`

func (q *Queries) ClaimPositionForClose(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, claimPositionForClose, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countOpenPositionsAllSymbols = `-- name: CountOpenPositionsAllSymbols :one
SELECT COUNT(*)::int8 AS count
FROM positions
WHERE status IN ('OPEN','CLOSING')
`

// Account-wide AccountOpenPositions cap reads this. Counts every
// OPEN+CLOSING position across all symbols, including external (manually-
// opened in the GMO app) positions — the account cap is a margin-protection
// gate so external positions consume the same margin pool.
func (q *Queries) CountOpenPositionsAllSymbols(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenPositionsAllSymbols)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const extendPositionMaxHold = `-- name: ExtendPositionMaxHold :one
UPDATE positions
SET max_hold_minutes = max_hold_minutes + $1,
    updated_at = now()
WHERE id = $2 AND status = 'OPEN'
RETURNING max_hold_minutes, opened_at
`

type ExtendPositionMaxHoldParams struct {
	AddMinutes int32
	ID         int64
}

type ExtendPositionMaxHoldRow struct {
	MaxHoldMinutes int32
	OpenedAt       pgtype.Timestamptz
}

// 延長ボタン (UI: POST /api/positions/extend) から呼ぶ。max_hold_minutes に
// add_minutes を加算し、新しい合計 + opened_at を返す。status='OPEN' の row
// のみ対象。CLOSING/CLOSED/未知 id は 0 rows → :one が pgx.ErrNoRows を返し、
// wrapper が nil で「対象なし」を表す。bot の OnTick は毎 tick で
// max_hold_minutes を読み直すので、UPDATE 後の次 tick から新 deadline が効く
// (build/close 不要)。max_hold_minutes は per-position の凍結値なので config
// 変更では動かせない (建玉時に凍結保存した値を使う設計)。
func (q *Queries) ExtendPositionMaxHold(ctx context.Context, arg ExtendPositionMaxHoldParams) (ExtendPositionMaxHoldRow, error) {
	row := q.db.QueryRow(ctx, extendPositionMaxHold, arg.AddMinutes, arg.ID)
	var i ExtendPositionMaxHoldRow
	err := row.Scan(&i.MaxHoldMinutes, &i.OpenedAt)
	return i, err
}

const getPositionLive = `-- name: GetPositionLive :one
SELECT position_id, broker_position_id, tp_order_id, sl_order_id
FROM positions_live
WHERE position_id = $1
`

func (q *Queries) GetPositionLive(ctx context.Context, positionID int64) (PositionsLive, error) {
	row := q.db.QueryRow(ctx, getPositionLive, positionID)
	var i PositionsLive
	err := row.Scan(
		&i.PositionID,
		&i.BrokerPositionID,
		&i.TpOrderID,
		&i.SlOrderID,
	)
	return i, err
}

const insertManualPosition = `-- name: InsertManualPosition :exec
INSERT INTO manual_positions (position_id) VALUES ($1)
`

func (q *Queries) InsertManualPosition(ctx context.Context, positionID int64) error {
	_, err := q.db.Exec(ctx, insertManualPosition, positionID)
	return err
}

const insertPosition = `-- name: InsertPosition :one
INSERT INTO positions (
  symbol, side, quantity, entry_price,
  take_profit_pips, stop_loss_pips, max_hold_minutes,
  extension_max_minutes, extension_unrealized_pips_threshold,
  early_exit_window_minutes, early_exit_target_pips,
  ratchet_arm_pips, ratchet_giveback_pips,
  entry_fee_jpy, entry_spread_pips, entry_slippage_pips,
  strategy_config_id, status, opened_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19)
RETURNING id
`

type InsertPositionParams struct {
	Symbol                           string
	Side                             string
	Quantity                         int32
	EntryPrice                       float64
	TakeProfitPips                   float64
	StopLossPips                     float64
	MaxHoldMinutes                   int32
	ExtensionMaxMinutes              int32
	ExtensionUnrealizedPipsThreshold float64
	EarlyExitWindowMinutes           int32
	EarlyExitTargetPips              float64
	RatchetArmPips                   float64
	RatchetGivebackPips              float64
	EntryFeeJpy                      *float64
	EntrySpreadPips                  *float64
	EntrySlippagePips                *float64
	StrategyConfigID                 string
	Status                           string
	OpenedAt                         pgtype.Timestamptz
}

// ratchet_arm_pips / ratchet_giveback_pips は snapshot for trailing
// take-profit (migration 0003). peak_unrealized_pips / ratchet_armed は
// runtime state なので INSERT 時は DEFAULT (0/false) のまま。OnTick で
// UpdatePositionRatchetState が更新する。
// entry_fee_jpy / entry_spread_pips / entry_slippage_pips は entry 時点の
// 実コスト捕捉 (migration 0008)。NULL = 未捕捉 (0 と区別)。
func (q *Queries) InsertPosition(ctx context.Context, arg InsertPositionParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertPosition,
		arg.Symbol,
		arg.Side,
		arg.Quantity,
		arg.EntryPrice,
		arg.TakeProfitPips,
		arg.StopLossPips,
		arg.MaxHoldMinutes,
		arg.ExtensionMaxMinutes,
		arg.ExtensionUnrealizedPipsThreshold,
		arg.EarlyExitWindowMinutes,
		arg.EarlyExitTargetPips,
		arg.RatchetArmPips,
		arg.RatchetGivebackPips,
		arg.EntryFeeJpy,
		arg.EntrySpreadPips,
		arg.EntrySlippagePips,
		arg.StrategyConfigID,
		arg.Status,
		arg.OpenedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPositionLive = `-- name: InsertPositionLive :exec
INSERT INTO positions_live (position_id, broker_position_id, tp_order_id, sl_order_id)
VALUES ($1, $2, $3, $4)
`

type InsertPositionLiveParams struct {
	PositionID       int64
	BrokerPositionID string
	TpOrderID        string
	SlOrderID        string
}

func (q *Queries) InsertPositionLive(ctx context.Context, arg InsertPositionLiveParams) error {
	_, err := q.db.Exec(ctx, insertPositionLive,
		arg.PositionID,
		arg.BrokerPositionID,
		arg.TpOrderID,
		arg.SlOrderID,
	)
	return err
}

const insertPositionStateEvent = `-- name: InsertPositionStateEvent :exec
INSERT INTO position_state_events (position_id, state, transitioned_at)
VALUES ($1, $2, $3)
`

type InsertPositionStateEventParams struct {
	PositionID     int64
	State          string
	TransitionedAt pgtype.Timestamptz
}

func (q *Queries) InsertPositionStateEvent(ctx context.Context, arg InsertPositionStateEventParams) error {
	_, err := q.db.Exec(ctx, insertPositionStateEvent, arg.PositionID, arg.State, arg.TransitionedAt)
	return err
}

const insertRecoveredPosition = `-- name: InsertRecoveredPosition :exec
INSERT INTO recovered_positions (position_id, recovery_reason, recovered_at)
VALUES ($1, $2, $3)
`

type InsertRecoveredPositionParams struct {
	PositionID     int64
	RecoveryReason string
	RecoveredAt    pgtype.Timestamptz
}

func (q *Queries) InsertRecoveredPosition(ctx context.Context, arg InsertRecoveredPositionParams) error {
	_, err := q.db.Exec(ctx, insertRecoveredPosition, arg.PositionID, arg.RecoveryReason, arg.RecoveredAt)
	return err
}

const isManualPosition = `-- name: IsManualPosition :one
SELECT EXISTS (SELECT 1 FROM manual_positions WHERE position_id = $1) AS is_manual
`

func (q *Queries) IsManualPosition(ctx context.Context, positionID int64) (bool, error) {
	row := q.db.QueryRow(ctx, isManualPosition, positionID)
	var is_manual bool
	err := row.Scan(&is_manual)
	return is_manual, err
}

const listOpenOrClosingPositions = `-- name: ListOpenOrClosingPositions :many
SELECT p.id, p.symbol, p.side, p.quantity, p.entry_price,
       p.take_profit_pips, p.stop_loss_pips, p.max_hold_minutes,
       p.extension_max_minutes, p.extension_unrealized_pips_threshold,
       p.early_exit_window_minutes, p.early_exit_target_pips,
       p.ratchet_arm_pips, p.ratchet_giveback_pips,
       p.peak_unrealized_pips, p.ratchet_armed,
       p.trough_unrealized_pips, p.loss_ratchet_armed,
       p.entry_fee_jpy, p.entry_spread_pips, p.entry_slippage_pips,
       p.strategy_config_id, p.status, p.opened_at,
       COALESCE(r.recovery_reason, '')::text AS recovery_reason
FROM positions p
LEFT JOIN recovered_positions r ON r.position_id = p.id
WHERE p.status IN ('OPEN','CLOSING') AND ($1::text = '' OR p.symbol = $1)
ORDER BY p.opened_at ASC
`

type ListOpenOrClosingPositionsRow struct {
	ID                               int64
	Symbol                           string
	Side                             string
	Quantity                         int32
	EntryPrice                       float64
	TakeProfitPips                   float64
	StopLossPips                     float64
	MaxHoldMinutes                   int32
	ExtensionMaxMinutes              int32
	ExtensionUnrealizedPipsThreshold float64
	EarlyExitWindowMinutes           int32
	EarlyExitTargetPips              float64
	RatchetArmPips                   float64
	RatchetGivebackPips              float64
	PeakUnrealizedPips               float64
	RatchetArmed                     bool
	TroughUnrealizedPips             float64
	LossRatchetArmed                 bool
	EntryFeeJpy                      *float64
	EntrySpreadPips                  *float64
	EntrySlippagePips                *float64
	StrategyConfigID                 string
	Status                           string
	OpenedAt                         pgtype.Timestamptz
	RecoveryReason                   string
}

// LEFT JOIN recovered_positions so the row carries the recovery_reason
// (empty string when the row has no recovered_positions junction). The
// repo wrapper maps reason → port.PositionSource so usecase code never
// branches on the raw string.
func (q *Queries) ListOpenOrClosingPositions(ctx context.Context, dollar_1 string) ([]ListOpenOrClosingPositionsRow, error) {
	rows, err := q.db.Query(ctx, listOpenOrClosingPositions, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenOrClosingPositionsRow
	for rows.Next() {
		var i ListOpenOrClosingPositionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.Side,
			&i.Quantity,
			&i.EntryPrice,
			&i.TakeProfitPips,
			&i.StopLossPips,
			&i.MaxHoldMinutes,
			&i.ExtensionMaxMinutes,
			&i.ExtensionUnrealizedPipsThreshold,
			&i.EarlyExitWindowMinutes,
			&i.EarlyExitTargetPips,
			&i.RatchetArmPips,
			&i.RatchetGivebackPips,
			&i.PeakUnrealizedPips,
			&i.RatchetArmed,
			&i.TroughUnrealizedPips,
			&i.LossRatchetArmed,
			&i.EntryFeeJpy,
			&i.EntrySpreadPips,
			&i.EntrySlippagePips,
			&i.StrategyConfigID,
			&i.Status,
			&i.OpenedAt,
			&i.RecoveryReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPositionClosed = `-- name: MarkPositionClosed :execrows
UPDATE positions
SET status = 'CLOSED', updated_at = now()
WHERE id = $1 AND status = 'CLOSING'
`

func (q *Queries) MarkPositionClosed(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, markPositionClosed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markPositionClosedBlind = `-- name: MarkPositionClosedBlind :execrows
UPDATE positions
SET status = 'CLOSED', updated_at = now()
WHERE id = $1 AND status IN ('OPEN','CLOSING')
`

// Paper-startup-only blind close path. Lossy: no trade row is written.
// Live MUST go through MarkPositionClosed (CLOSING → CLOSED) inside the
// PositionCloser Tx so the trade ledger stays complete.
func (q *Queries) MarkPositionClosedBlind(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, markPositionClosedBlind, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePositionRatchetState = `-- name: UpdatePositionRatchetState :execrows
UPDATE positions
SET peak_unrealized_pips = $2,
    ratchet_armed = $3,
    trough_unrealized_pips = $4,
    loss_ratchet_armed = $5,
    updated_at = now()
WHERE id = $1 AND status = 'OPEN'
`

type UpdatePositionRatchetStateParams struct {
	ID                   int64
	PeakUnrealizedPips   float64
	RatchetArmed         bool
	TroughUnrealizedPips float64
	LossRatchetArmed     bool
}

// OnTick で利確側 (peak/armed) と損切り側 (trough/loss_armed) の ratchet
// runtime state を 1 write で更新する。armed/loss_armed は monotonic
// (false→true)、peak は monotonic increasing・trough は monotonic decreasing
// で usecase 側が保証する。status='OPEN' の row のみ更新 (CLOSING 中の
// position は close saga が値を確定させているので state update は無視)。
func (q *Queries) UpdatePositionRatchetState(ctx context.Context, arg UpdatePositionRatchetStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePositionRatchetState,
		arg.ID,
		arg.PeakUnrealizedPips,
		arg.RatchetArmed,
		arg.TroughUnrealizedPips,
		arg.LossRatchetArmed,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
