// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: signal_rejections.sql

package dbgen

import (
	"context"
)

const insertSignalRejection = `-- name: InsertSignalRejection :exec
INSERT INTO signal_rejections (strategy_config_id, reason, detail)
VALUES ($1, $2, $3)
`

type InsertSignalRejectionParams struct {
	StrategyConfigID string
	Reason           string
	Detail           []byte
}

func (q *Queries) InsertSignalRejection(ctx context.Context, arg InsertSignalRejectionParams) error {
	_, err := q.db.Exec(ctx, insertSignalRejection, arg.StrategyConfigID, arg.Reason, arg.Detail)
	return err
}
