// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: strategy_configs.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const expireOtherActiveConfigs = `-- name: ExpireOtherActiveConfigs :exec
UPDATE strategy_configs
SET status = 'expired'
WHERE symbol = $1 AND mode = $2 AND status = 'active' AND config_id <> $3
`

type ExpireOtherActiveConfigsParams struct {
	Symbol   string
	Mode     string
	ConfigID string
}

func (q *Queries) ExpireOtherActiveConfigs(ctx context.Context, arg ExpireOtherActiveConfigsParams) error {
	_, err := q.db.Exec(ctx, expireOtherActiveConfigs, arg.Symbol, arg.Mode, arg.ConfigID)
	return err
}

const getActiveStrategyConfig = `-- name: GetActiveStrategyConfig :one
SELECT sc.config_id, sc.source, sc.mode, sc.symbol, sc.enabled,
       COALESCE(sc.market_regime_type,'')::text AS market_regime_type,
       sc.market_regime_confidence,
       COALESCE(sc.strategy_name,'')::text AS strategy_name,
       sc.valid_from, sc.valid_until, sc.raw_yaml,
       sc.status, COALESCE(sr.reason,'')::text AS reject_reason
FROM strategy_configs sc
LEFT JOIN strategy_config_rejections   sr ON sr.config_id = sc.config_id
LEFT JOIN strategy_config_activations  sa ON sa.config_id = sc.config_id
WHERE sc.status = 'active' AND sc.symbol = $1 AND sc.mode = $2
ORDER BY sa.activated_at DESC NULLS LAST, sc.id DESC
LIMIT 1
`

type GetActiveStrategyConfigParams struct {
	Symbol string
	Mode   string
}

type GetActiveStrategyConfigRow struct {
	ConfigID               string
	Source                 string
	Mode                   string
	Symbol                 string
	Enabled                bool
	MarketRegimeType       string
	MarketRegimeConfidence float64
	StrategyName           string
	ValidFrom              pgtype.Timestamptz
	ValidUntil             pgtype.Timestamptz
	RawYaml                string
	Status                 string
	RejectReason           string
}

func (q *Queries) GetActiveStrategyConfig(ctx context.Context, arg GetActiveStrategyConfigParams) (GetActiveStrategyConfigRow, error) {
	row := q.db.QueryRow(ctx, getActiveStrategyConfig, arg.Symbol, arg.Mode)
	var i GetActiveStrategyConfigRow
	err := row.Scan(
		&i.ConfigID,
		&i.Source,
		&i.Mode,
		&i.Symbol,
		&i.Enabled,
		&i.MarketRegimeType,
		&i.MarketRegimeConfidence,
		&i.StrategyName,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.RawYaml,
		&i.Status,
		&i.RejectReason,
	)
	return i, err
}

const insertStrategyConfig = `-- name: InsertStrategyConfig :exec
INSERT INTO strategy_configs (
  config_id, source, mode, symbol, enabled,
  market_regime_type, market_regime_confidence, strategy_name,
  valid_from, valid_until, raw_yaml, status
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type InsertStrategyConfigParams struct {
	ConfigID               string
	Source                 string
	Mode                   string
	Symbol                 string
	Enabled                bool
	MarketRegimeType       *string
	MarketRegimeConfidence float64
	StrategyName           *string
	ValidFrom              pgtype.Timestamptz
	ValidUntil             pgtype.Timestamptz
	RawYaml                string
	Status                 string
}

// market_regime_type / strategy_name accept *string (nil = NULL) so the
// wrapper can map "" to NULL without sqlc losing the column type.
func (q *Queries) InsertStrategyConfig(ctx context.Context, arg InsertStrategyConfigParams) error {
	_, err := q.db.Exec(ctx, insertStrategyConfig,
		arg.ConfigID,
		arg.Source,
		arg.Mode,
		arg.Symbol,
		arg.Enabled,
		arg.MarketRegimeType,
		arg.MarketRegimeConfidence,
		arg.StrategyName,
		arg.ValidFrom,
		arg.ValidUntil,
		arg.RawYaml,
		arg.Status,
	)
	return err
}

const listRecentStrategyConfigs = `-- name: ListRecentStrategyConfigs :many
SELECT sc.config_id, sc.source, sc.mode, sc.symbol, sc.enabled,
       COALESCE(sc.market_regime_type,'')::text AS market_regime_type,
       sc.market_regime_confidence,
       COALESCE(sc.strategy_name,'')::text AS strategy_name,
       sc.valid_from, sc.valid_until, sc.raw_yaml,
       sc.status, COALESCE(sr.reason,'')::text AS reject_reason,
       sc.created_at, sa.activated_at
FROM strategy_configs sc
LEFT JOIN strategy_config_rejections   sr ON sr.config_id = sc.config_id
LEFT JOIN strategy_config_activations  sa ON sa.config_id = sc.config_id
ORDER BY sc.created_at DESC
LIMIT $1
`

type ListRecentStrategyConfigsRow struct {
	ConfigID               string
	Source                 string
	Mode                   string
	Symbol                 string
	Enabled                bool
	MarketRegimeType       string
	MarketRegimeConfidence float64
	StrategyName           string
	ValidFrom              pgtype.Timestamptz
	ValidUntil             pgtype.Timestamptz
	RawYaml                string
	Status                 string
	RejectReason           string
	CreatedAt              pgtype.Timestamptz
	ActivatedAt            pgtype.Timestamptz
}

func (q *Queries) ListRecentStrategyConfigs(ctx context.Context, limit int32) ([]ListRecentStrategyConfigsRow, error) {
	rows, err := q.db.Query(ctx, listRecentStrategyConfigs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentStrategyConfigsRow
	for rows.Next() {
		var i ListRecentStrategyConfigsRow
		if err := rows.Scan(
			&i.ConfigID,
			&i.Source,
			&i.Mode,
			&i.Symbol,
			&i.Enabled,
			&i.MarketRegimeType,
			&i.MarketRegimeConfidence,
			&i.StrategyName,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.RawYaml,
			&i.Status,
			&i.RejectReason,
			&i.CreatedAt,
			&i.ActivatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStrategyConfigActive = `-- name: MarkStrategyConfigActive :exec
UPDATE strategy_configs SET status = 'active' WHERE config_id = $1
`

func (q *Queries) MarkStrategyConfigActive(ctx context.Context, configID string) error {
	_, err := q.db.Exec(ctx, markStrategyConfigActive, configID)
	return err
}

const markStrategyConfigExpired = `-- name: MarkStrategyConfigExpired :exec
UPDATE strategy_configs
SET status = 'expired'
WHERE config_id = $1 AND status = 'active'
`

func (q *Queries) MarkStrategyConfigExpired(ctx context.Context, configID string) error {
	_, err := q.db.Exec(ctx, markStrategyConfigExpired, configID)
	return err
}

const upsertStrategyConfigActivation = `-- name: UpsertStrategyConfigActivation :exec
INSERT INTO strategy_config_activations (config_id, activated_at)
VALUES ($1, $2)
ON CONFLICT (config_id) DO UPDATE SET activated_at = EXCLUDED.activated_at
`

type UpsertStrategyConfigActivationParams struct {
	ConfigID    string
	ActivatedAt pgtype.Timestamptz
}

func (q *Queries) UpsertStrategyConfigActivation(ctx context.Context, arg UpsertStrategyConfigActivationParams) error {
	_, err := q.db.Exec(ctx, upsertStrategyConfigActivation, arg.ConfigID, arg.ActivatedAt)
	return err
}

const upsertStrategyConfigParseFailure = `-- name: UpsertStrategyConfigParseFailure :exec
INSERT INTO strategy_config_parse_failures (config_id, raw_input)
VALUES ($1, $2)
ON CONFLICT (config_id) DO UPDATE SET raw_input = EXCLUDED.raw_input
`

type UpsertStrategyConfigParseFailureParams struct {
	ConfigID string
	RawInput string
}

func (q *Queries) UpsertStrategyConfigParseFailure(ctx context.Context, arg UpsertStrategyConfigParseFailureParams) error {
	_, err := q.db.Exec(ctx, upsertStrategyConfigParseFailure, arg.ConfigID, arg.RawInput)
	return err
}

const upsertStrategyConfigRejection = `-- name: UpsertStrategyConfigRejection :exec
INSERT INTO strategy_config_rejections (config_id, reason)
VALUES ($1, $2)
ON CONFLICT (config_id) DO UPDATE SET reason = EXCLUDED.reason
`

type UpsertStrategyConfigRejectionParams struct {
	ConfigID string
	Reason   string
}

func (q *Queries) UpsertStrategyConfigRejection(ctx context.Context, arg UpsertStrategyConfigRejectionParams) error {
	_, err := q.db.Exec(ctx, upsertStrategyConfigRejection, arg.ConfigID, arg.Reason)
	return err
}
