// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trades.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countClosedBySymbolSince = `-- name: CountClosedBySymbolSince :one
SELECT COUNT(*)::int8 AS count
FROM trades
WHERE symbol = $1 AND closed_at >= $2
`

type CountClosedBySymbolSinceParams struct {
	Symbol   string
	ClosedAt pgtype.Timestamptz
}

// Per-symbol closed-trade count for MaxTradesInThisWindow per-symbol cap.
func (q *Queries) CountClosedBySymbolSince(ctx context.Context, arg CountClosedBySymbolSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countClosedBySymbolSince, arg.Symbol, arg.ClosedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countClosedSince = `-- name: CountClosedSince :one
SELECT COUNT(*)::int8 AS count
FROM trades
WHERE closed_at >= $1
`

func (q *Queries) CountClosedSince(ctx context.Context, closedAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countClosedSince, closedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEarlyExitTradesSinceBySymbol = `-- name: CountEarlyExitTradesSinceBySymbol :one
SELECT COUNT(*)::int8 AS count
FROM trades t
WHERE t.symbol = $1
  AND t.closed_at >= $2
  AND t.close_reason = 'early_exit'
`

type CountEarlyExitTradesSinceBySymbolParams struct {
	Symbol   string
	ClosedAt pgtype.Timestamptz
}

// Dashboard: early-exit window 発火で close したトレード数。
// close_reason='early_exit' を直接カウントする (ラベルは migration 0005 で追加)。
// ラベル追加前の early-exit は 'max_hold' に混ざっているため遡及されない (= go-forward
// 集計)。
func (q *Queries) CountEarlyExitTradesSinceBySymbol(ctx context.Context, arg CountEarlyExitTradesSinceBySymbolParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEarlyExitTradesSinceBySymbol, arg.Symbol, arg.ClosedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOpenedSince = `-- name: CountOpenedSince :one
SELECT COUNT(*)::int8 AS count
FROM trades
WHERE opened_at >= $1
`

func (q *Queries) CountOpenedSince(ctx context.Context, openedAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenedSince, openedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertTrade = `-- name: InsertTrade :one
INSERT INTO trades (
  position_id, strategy_config_id, symbol, side, quantity,
  entry_price, exit_price, profit_loss_pips, profit_loss_jpy,
  close_reason, fee_jpy, swap_jpy, fee_estimated, opened_at, closed_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id
`

type InsertTradeParams struct {
	PositionID       int64
	StrategyConfigID string
	Symbol           string
	Side             string
	Quantity         int32
	EntryPrice       float64
	ExitPrice        float64
	ProfitLossPips   float64
	ProfitLossJpy    float64
	CloseReason      string
	FeeJpy           float64
	SwapJpy          float64
	FeeEstimated     bool
	OpenedAt         pgtype.Timestamptz
	ClosedAt         pgtype.Timestamptz
}

// fee_jpy / swap_jpy / fee_estimated は migration 0007 列。
// profit_loss_jpy は GROSS のまま — net は導出側 (edge_metrics) で計算する。
func (q *Queries) InsertTrade(ctx context.Context, arg InsertTradeParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertTrade,
		arg.PositionID,
		arg.StrategyConfigID,
		arg.Symbol,
		arg.Side,
		arg.Quantity,
		arg.EntryPrice,
		arg.ExitPrice,
		arg.ProfitLossPips,
		arg.ProfitLossJpy,
		arg.CloseReason,
		arg.FeeJpy,
		arg.SwapJpy,
		arg.FeeEstimated,
		arg.OpenedAt,
		arg.ClosedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertTradeSignal = `-- name: InsertTradeSignal :exec
INSERT INTO trade_signals (trade_id, signal_id) VALUES ($1, $2)
`

type InsertTradeSignalParams struct {
	TradeID  int64
	SignalID string
}

func (q *Queries) InsertTradeSignal(ctx context.Context, arg InsertTradeSignalParams) error {
	_, err := q.db.Exec(ctx, insertTradeSignal, arg.TradeID, arg.SignalID)
	return err
}

const listTradesClosedBySymbolSince = `-- name: ListTradesClosedBySymbolSince :many
SELECT t.position_id, COALESCE(ts.signal_id,'')::text AS signal_id,
       t.strategy_config_id, t.symbol, t.side, t.quantity,
       t.entry_price, t.exit_price, t.profit_loss_pips, t.profit_loss_jpy,
       t.close_reason, t.fee_jpy, t.swap_jpy, t.fee_estimated,
       t.opened_at, t.closed_at,
       (CASE
          WHEN mp.position_id IS NOT NULL THEN 'manual'
          WHEN rp.recovery_reason = 'external_broker_adoption' THEN 'external'
          ELSE 'bot'
        END)::text AS origin
FROM trades t
LEFT JOIN trade_signals ts ON ts.trade_id = t.id
LEFT JOIN manual_positions mp ON mp.position_id = t.position_id
LEFT JOIN recovered_positions rp ON rp.position_id = t.position_id
WHERE t.symbol = $1 AND t.closed_at >= $2
ORDER BY t.closed_at DESC
LIMIT $3
`

type ListTradesClosedBySymbolSinceParams struct {
	Symbol   string
	ClosedAt pgtype.Timestamptz
	Limit    int32
}

type ListTradesClosedBySymbolSinceRow struct {
	PositionID       int64
	SignalID         string
	StrategyConfigID string
	Symbol           string
	Side             string
	Quantity         int32
	EntryPrice       float64
	ExitPrice        float64
	ProfitLossPips   float64
	ProfitLossJpy    float64
	CloseReason      string
	FeeJpy           float64
	SwapJpy          float64
	FeeEstimated     bool
	OpenedAt         pgtype.Timestamptz
	ClosedAt         pgtype.Timestamptz
	Origin           string
}

// Per-symbol close ledger for the risk gate's per-symbol caps. Mirrors
// ListTradesClosedSince but filters by symbol so a sibling symbol's
// trades cannot pollute this bundle's MaxLossInThisWindow / MaxTradesInWindow.
func (q *Queries) ListTradesClosedBySymbolSince(ctx context.Context, arg ListTradesClosedBySymbolSinceParams) ([]ListTradesClosedBySymbolSinceRow, error) {
	rows, err := q.db.Query(ctx, listTradesClosedBySymbolSince, arg.Symbol, arg.ClosedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTradesClosedBySymbolSinceRow
	for rows.Next() {
		var i ListTradesClosedBySymbolSinceRow
		if err := rows.Scan(
			&i.PositionID,
			&i.SignalID,
			&i.StrategyConfigID,
			&i.Symbol,
			&i.Side,
			&i.Quantity,
			&i.EntryPrice,
			&i.ExitPrice,
			&i.ProfitLossPips,
			&i.ProfitLossJpy,
			&i.CloseReason,
			&i.FeeJpy,
			&i.SwapJpy,
			&i.FeeEstimated,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.Origin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTradesClosedSince = `-- name: ListTradesClosedSince :many
SELECT t.position_id, COALESCE(ts.signal_id,'')::text AS signal_id,
       t.strategy_config_id, t.symbol, t.side, t.quantity,
       t.entry_price, t.exit_price, t.profit_loss_pips, t.profit_loss_jpy,
       t.close_reason, t.fee_jpy, t.swap_jpy, t.fee_estimated,
       t.opened_at, t.closed_at,
       (CASE
          WHEN mp.position_id IS NOT NULL THEN 'manual'
          WHEN rp.recovery_reason = 'external_broker_adoption' THEN 'external'
          ELSE 'bot'
        END)::text AS origin
FROM trades t
LEFT JOIN trade_signals ts ON ts.trade_id = t.id
LEFT JOIN manual_positions mp ON mp.position_id = t.position_id
LEFT JOIN recovered_positions rp ON rp.position_id = t.position_id
WHERE t.closed_at >= $1
ORDER BY t.closed_at DESC
LIMIT $2
`

type ListTradesClosedSinceParams struct {
	ClosedAt pgtype.Timestamptz
	Limit    int32
}

type ListTradesClosedSinceRow struct {
	PositionID       int64
	SignalID         string
	StrategyConfigID string
	Symbol           string
	Side             string
	Quantity         int32
	EntryPrice       float64
	ExitPrice        float64
	ProfitLossPips   float64
	ProfitLossJpy    float64
	CloseReason      string
	FeeJpy           float64
	SwapJpy          float64
	FeeEstimated     bool
	OpenedAt         pgtype.Timestamptz
	ClosedAt         pgtype.Timestamptz
	Origin           string
}

func (q *Queries) ListTradesClosedSince(ctx context.Context, arg ListTradesClosedSinceParams) ([]ListTradesClosedSinceRow, error) {
	rows, err := q.db.Query(ctx, listTradesClosedSince, arg.ClosedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTradesClosedSinceRow
	for rows.Next() {
		var i ListTradesClosedSinceRow
		if err := rows.Scan(
			&i.PositionID,
			&i.SignalID,
			&i.StrategyConfigID,
			&i.Symbol,
			&i.Side,
			&i.Quantity,
			&i.EntryPrice,
			&i.ExitPrice,
			&i.ProfitLossPips,
			&i.ProfitLossJpy,
			&i.CloseReason,
			&i.FeeJpy,
			&i.SwapJpy,
			&i.FeeEstimated,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.Origin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTradesSinceOpened = `-- name: ListTradesSinceOpened :many
SELECT t.position_id, COALESCE(ts.signal_id,'')::text AS signal_id,
       t.strategy_config_id, t.symbol, t.side, t.quantity,
       t.entry_price, t.exit_price, t.profit_loss_pips, t.profit_loss_jpy,
       t.close_reason, t.fee_jpy, t.swap_jpy, t.fee_estimated,
       t.opened_at, t.closed_at,
       (CASE
          WHEN mp.position_id IS NOT NULL THEN 'manual'
          WHEN rp.recovery_reason = 'external_broker_adoption' THEN 'external'
          ELSE 'bot'
        END)::text AS origin
FROM trades t
LEFT JOIN trade_signals ts ON ts.trade_id = t.id
LEFT JOIN manual_positions mp ON mp.position_id = t.position_id
LEFT JOIN recovered_positions rp ON rp.position_id = t.position_id
WHERE t.opened_at >= $1
ORDER BY t.opened_at DESC
LIMIT $2
`

type ListTradesSinceOpenedParams struct {
	OpenedAt pgtype.Timestamptz
	Limit    int32
}

type ListTradesSinceOpenedRow struct {
	PositionID       int64
	SignalID         string
	StrategyConfigID string
	Symbol           string
	Side             string
	Quantity         int32
	EntryPrice       float64
	ExitPrice        float64
	ProfitLossPips   float64
	ProfitLossJpy    float64
	CloseReason      string
	FeeJpy           float64
	SwapJpy          float64
	FeeEstimated     bool
	OpenedAt         pgtype.Timestamptz
	ClosedAt         pgtype.Timestamptz
	Origin           string
}

// origin discriminates bot trades from the operator's own discretionary
// trades (manual_trade command = manual_positions; GMO-app entry adopted by
// reconcile = recovered_positions.external_broker_adoption). The trades row's
// strategy_config_id only borrows the active config as an FK target, so this
// read-time JOIN is what keeps the dashboard label / edge metrics honest.
func (q *Queries) ListTradesSinceOpened(ctx context.Context, arg ListTradesSinceOpenedParams) ([]ListTradesSinceOpenedRow, error) {
	rows, err := q.db.Query(ctx, listTradesSinceOpened, arg.OpenedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTradesSinceOpenedRow
	for rows.Next() {
		var i ListTradesSinceOpenedRow
		if err := rows.Scan(
			&i.PositionID,
			&i.SignalID,
			&i.StrategyConfigID,
			&i.Symbol,
			&i.Side,
			&i.Quantity,
			&i.EntryPrice,
			&i.ExitPrice,
			&i.ProfitLossPips,
			&i.ProfitLossJpy,
			&i.CloseReason,
			&i.FeeJpy,
			&i.SwapJpy,
			&i.FeeEstimated,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.Origin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumClosedLossJPYBySymbolSince = `-- name: SumClosedLossJPYBySymbolSince :one
SELECT COALESCE(SUM(CASE WHEN (profit_loss_jpy - fee_jpy + swap_jpy) < 0 THEN -(profit_loss_jpy - fee_jpy + swap_jpy) ELSE 0 END), 0)::float8 AS loss_jpy
FROM trades
WHERE symbol = $1 AND closed_at >= $2
`

type SumClosedLossJPYBySymbolSinceParams struct {
	Symbol   string
	ClosedAt pgtype.Timestamptz
}

// Per-symbol loss aggregate for MaxLossInThisWindowJPY / MaxDailyLossJPY
// per-symbol caps.
// NET of GMO fee + swap (= real money lost): a gross-positive trade eaten by the fee counts as a loss.
func (q *Queries) SumClosedLossJPYBySymbolSince(ctx context.Context, arg SumClosedLossJPYBySymbolSinceParams) (float64, error) {
	row := q.db.QueryRow(ctx, sumClosedLossJPYBySymbolSince, arg.Symbol, arg.ClosedAt)
	var loss_jpy float64
	err := row.Scan(&loss_jpy)
	return loss_jpy, err
}

const sumClosedLossJPYSince = `-- name: SumClosedLossJPYSince :one
SELECT COALESCE(SUM(CASE WHEN (profit_loss_jpy - fee_jpy + swap_jpy) < 0 THEN -(profit_loss_jpy - fee_jpy + swap_jpy) ELSE 0 END), 0)::float8 AS loss_jpy
FROM trades
WHERE closed_at >= $1
`

// NET of GMO fee + swap (= real money lost): a gross-positive trade eaten by the fee counts as a loss.
func (q *Queries) SumClosedLossJPYSince(ctx context.Context, closedAt pgtype.Timestamptz) (float64, error) {
	row := q.db.QueryRow(ctx, sumClosedLossJPYSince, closedAt)
	var loss_jpy float64
	err := row.Scan(&loss_jpy)
	return loss_jpy, err
}

const sumOpenedLossJPYSince = `-- name: SumOpenedLossJPYSince :one
SELECT COALESCE(SUM(CASE WHEN (profit_loss_jpy - fee_jpy + swap_jpy) < 0 THEN -(profit_loss_jpy - fee_jpy + swap_jpy) ELSE 0 END), 0)::float8 AS loss_jpy
FROM trades
WHERE opened_at >= $1
`

// NET of GMO fee + swap (= real money lost): a gross-positive trade eaten by the fee counts as a loss.
func (q *Queries) SumOpenedLossJPYSince(ctx context.Context, openedAt pgtype.Timestamptz) (float64, error) {
	row := q.db.QueryRow(ctx, sumOpenedLossJPYSince, openedAt)
	var loss_jpy float64
	err := row.Scan(&loss_jpy)
	return loss_jpy, err
}

const sumPnLJPYClosedSinceBySymbol = `-- name: SumPnLJPYClosedSinceBySymbol :one
SELECT COALESCE(SUM(profit_loss_jpy - fee_jpy + swap_jpy), 0)::float8 AS pnl_jpy
FROM trades
WHERE symbol = $1 AND closed_at >= $2
`

type SumPnLJPYClosedSinceBySymbolParams struct {
	Symbol   string
	ClosedAt pgtype.Timestamptz
}

// Dashboard 用: symbol-scoped 直近 24h 実現 PnL。NET of GMO fee + swap.
func (q *Queries) SumPnLJPYClosedSinceBySymbol(ctx context.Context, arg SumPnLJPYClosedSinceBySymbolParams) (float64, error) {
	row := q.db.QueryRow(ctx, sumPnLJPYClosedSinceBySymbol, arg.Symbol, arg.ClosedAt)
	var pnl_jpy float64
	err := row.Scan(&pnl_jpy)
	return pnl_jpy, err
}
