// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: validation_events.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countValidationFailSince = `-- name: CountValidationFailSince :one
SELECT COUNT(*)::int8 AS count
FROM config_validation_events
WHERE status = 'fail' AND created_at >= $1
`

// Dashboard 用: 直近 24h の reject 件数。
func (q *Queries) CountValidationFailSince(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countValidationFailSince, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertConfigValidationEvent = `-- name: InsertConfigValidationEvent :exec
INSERT INTO config_validation_events (config_id, validation_type, status, message)
VALUES ($1, $2, $3, $4)
`

type InsertConfigValidationEventParams struct {
	ConfigID       string
	ValidationType string
	Status         string
	Message        *string
}

// message is nullable; pass *string (nil = NULL) from the wrapper.
func (q *Queries) InsertConfigValidationEvent(ctx context.Context, arg InsertConfigValidationEventParams) error {
	_, err := q.db.Exec(ctx, insertConfigValidationEvent,
		arg.ConfigID,
		arg.ValidationType,
		arg.Status,
		arg.Message,
	)
	return err
}
